### ISSUE TITLE
Cannot use select query 

### ISSUE THREAD

**Issue by mrakotomizao** [yoramdelangen/laravel-pdo-odbc#5]
When using select query, i'm getting following error 
`[unixODBC][Driver Manager]No columns were bound prior to calling SQLFetch or SQLFetchScroll (SQLFetchScroll[0] at /usr/src/php/ext/pdo_odbc/odbc_stmt.c:562)`

example query : ` $query = DB::connection('snowflake')->table('TEST')->where('COL', "=",'test')->get();` 

PHP version : 7.4| 8.0
Snowflake odbc version : 2.24.6

database config : 
```php
'snowflake' => [
            'driver' => 'snowflake',
            'odbc_driver' => '/usr/lib/snowflake/odbc/lib/libSnowflake.so',
            'server' => env('DB_SNOWFLAKE_SERVER', '127.0.0.1'),
            'username' => env('DB_SNOWFLAKE_USERNAME'),
            'role' => env('DB_SNOWFLAKE_ROLE'),
            'password' => env('DB_SNOWFLAKE_PASSWORD'),
            'database' => env('DB_SNOWFLAKE_DATABASE' ),
            'warehouse' => env('DB_SNOWFLAKE_WAREHOUSE'),
            'schema' => env('DB_SNOWFLAKE_SCHEMA'),
],

**Comment by madhukantmaurya** [comment]
I am getting the same issue on my side.

Let me know if anyone resolves this issue and how..?

**Comment by bmtKIA6** [comment]
Same....

**Comment by yoramdelangen** [comment]
@bmtKIA6 started on it in the `develop` branch

**Comment by yoramdelangen** [comment]
@mrakotomizao I did not have this issue anymore in the new version. Can you try to add the following options to your connection:
```php
  'options' => [
      \PDO::ODBC_ATTR_USE_CURSOR_LIBRARY => \PDO::ODBC_SQL_USE_DRIVER
  ]
```
This could be causing your problem

**Comment by yoramdelangen** [comment]
@mrakotomizao please checkout the develop branch for PHP 8 support.

**Comment by mrakotomizao** [comment]
Work for me too 👍
