### ISSUE TITLE
Driver Requirements

### ISSUE THREAD

**Issue by jesseschutt** [yoramdelangen/laravel-pdo-odbc#6]
Hello and thanks for your work on this package!

I'm exploring using Laravel to connect to Snowflake and curious if you can point me in any direction regarding what this package requires in terms of additional installations. For example, I have seen [this](https://github.com/snowflakedb/pdo_snowflake) and [this](https://docs.snowflake.com/en/user-guide/odbc-download.html). 

Which, if either, is required?

**Comment by yoramdelangen** [comment]
Thank you for using it! Currently, the Snowflake driver is not required.
This package came to life after researching for the driver of Snowflake. At the time they only supported PHP 7.2 and PHP 7.4 was already released. Hence this package connects via ODBC instead of using the Snowflake PDO driver. My intention is to start working on this package with Snowflake driver support. 

Currently, it's only working with PHP 7.4 which I have tested. Keeping you up-to-date

**Comment by dave-miller** [comment]
The main issue I had was connecting to snowflake, it took 3 full days to hack away at this. @yoramdelangen I am curious how you can connect via ODBC

**Comment by jesseschutt** [comment]
> Hence this package connects via ODBC instead of using the Snowflake PDO driver. My intention is to start working on this package with Snowflake driver support.

Ah, that's good to know! Does Laravel include the necessary drivers to support ODBC then?

> Currently, it's only working with PHP 7.4 which I have tested. Keeping you up-to-date

I'm interested in helping get it running on PHP 8.x if you are willing to have it.

**Comment by yoramdelangen** [comment]
> Ah, that's good to know! Does Laravel include the necessary drivers to support ODBC then? Or do we still need to use Snowflake's first-party ODBC driver?
No, only the generic ODBC drivers are needed (pdo_odbc and ODBC).

> I'm interested in helping get it running on PHP 8.x if you are willing to have it.
Any help is welcome and much appreciated!

**Comment by jesseschutt** [comment]
Thanks for clarification! 

>No, only the generic ODBC drivers are needed (pdo_odbc and ODBC)

Can you please link to an example of what you mean with these "generic ODBC" drivers? I've gone round and round with this so much I want to be sure I'm understanding what you are saying.

**Comment by jesseschutt** [comment]
Fantastic and thank you for your response @yoramdelangen!

Out of curiosity, what will change in the setup once you have completed the Snowflake driver you mentioned?

**Comment by yoramdelangen** [comment]
I hope for better performance, no weird behavior/bugs like documented in the README, easier [connection string definition](https://github.com/snowflakedb/pdo_snowflake/#connecting-to-the-snowflake-database). 

Currently, for me, it costs me 1-3 seconds for the most simplistic query to be executed. After a single query, it seems like Snowflake is closing the ODBC connection. So for every query, it has to "re-connect" with the server, and using an ORM like Eloquent does a lot of stuff in the background. For example; relationships are queried in 2/3 queries (rough 3-9seconds for maybe 10 records or so). 

Most of the time it's a large dataset of data and it will make the wait worth it

**Comment by madhukantmaurya** [comment]
Hello Guys,

I have installed the package as per the instruction but not getting how to get the "dsn" Driver path i.e 
/opt/snowflake_odbc/lib/libSnowflake.so

Please help me here

**Comment by yoramdelangen** [comment]
@madhukantmaurya what path did you put in? I recommend you use an odbc manager to create a connection and use that instead of inline.

**Comment by c00p3r** [comment]
Just gonna drop my dockerfile here
for those who's struggling
(I know you do :) I was for 2 days)
It includes official `pdo_snowflake` driver, odbc and pdo-odbc php extensions, phpredis and xdebug
with this - u're 100% ready to install the package
IT CANNOT USE ALPINE IMAGE!!!
because pdo_snowflake driver builds wrong

````
FROM php:7.4-fpm

WORKDIR /var/www

# install the jq library to support the snowflake build
RUN apt-get -y update \
    && apt-get -y install --no-install-recommends  \
    libicu-dev  \
    g++ \
    bash \
    httpie \
    unzip \
    libzip-dev \
    autoconf \
    make \
    jq \
    git \
    unixodbc \
    unixodbc-dev -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

RUN docker-php-ext-configure intl \
    && docker-php-ext-install intl pdo_mysql pcntl bcmath zip \
    && docker-php-ext-enable intl

# clone pdo_snowflake repo
RUN mkdir /tmp/snowflake \
    && git clone https://github.com/snowflakedb/pdo_snowflake.git /tmp/snowflake

# run the compile command
# move the compiled lib and cert to extensions dir
RUN export PHP_HOME=/usr/local \
    && bash /tmp/snowflake/scripts/build_pdo_snowflake.sh \
    && cp /tmp/snowflake/libsnowflakeclient/cacert.pem /tmp/snowflake/modules/pdo_snowflake.so /usr/local/lib/php/extensions/no-debug-non-zts-*/ \
    && rm -rf /tmp/snowflake

COPY ./docker/local/api/pdo_snowflake.ini /usr/local/etc/php/conf.d/pdo_snowflake.ini

RUN set -ex; \
    docker-php-source extract; \
    { \
        echo '# https://github.com/docker-library/php/issues/103#issuecomment-353674490'; \
        echo 'AC_DEFUN([PHP_ALWAYS_SHARED],[])dnl'; \
        echo; \
        cat /usr/src/php/ext/odbc/config.m4; \
    } > temp.m4; \
    mv temp.m4 /usr/src/php/ext/odbc/config.m4; \
    docker-php-ext-configure odbc --with-unixODBC=shared,/usr; \
    docker-php-ext-install odbc; \
    docker-php-source delete

RUN docker-php-ext-configure pdo_odbc --with-pdo-odbc=unixODBC,/usr \
    && docker-php-ext-install pdo_odbc

RUN pecl install -o -f redis \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable redis

ARG INSTALL_XDEBUG
ARG REMOTE_HOST_IP

RUN if [ "$INSTALL_XDEBUG" = "true" ];  \
    then \
    pecl install xdebug; \
    docker-php-ext-enable xdebug; \
fi

ENV COMPOSER_ALLOW_SUPERUSER 1

RUN curl -sS https://getcomposer.org/installer |  php -- --install-dir=/usr/local/bin --filename=composer

COPY ./docker/local/api/php.ini $PHP_INI_DIR/php.ini

COPY ./docker/local/api/www.conf $PHP_INI_DIR/../php-fpm.d/www.conf

RUN mkdir tests

## Composer - deps always cached unless changed
# First copy only composer files
COPY composer.* ./

# Download dependencies, but don't run scripts or init autoloaders as the app is missing
RUN composer install $COMPOSER_FLAGS --no-scripts --no-autoloader
# copy rest of the app
COPY . /code/
# run normal composer - all deps are cached already
RUN composer install $COMPOSER_FLAGS

COPY .env.example .env

COPY ./docker/local/api/entrypoint.sh /usr/local/bin

RUN ["chmod", "+x", "/usr/local/bin/entrypoint.sh"]

ENTRYPOINT ["/usr/local/bin/entrypoint.sh", "php-fpm"]

````
